### ISSUE TITLE
Ask for proxy usae

### ISSUE THREAD

**Issue by acbekoac** [realtho/PartyLoud#1]
Hi,

I wanted to use your tool not for hinding / mitigate tracking but testing a security proxy.

Ok, curl respects http_proxy variable but asking explicite for is IMHO quite nicer here.
So I just addes a few lines of code in a quick and dirty way. Please find my patch attached

[partyloud_patch.txt](https://github.com/realtho/PartyLoud/files/3084570/partyloud_patch.txt)

**Comment by realtho** [comment]
Thanks for the feedback, I'll add this feature in the next release. I found your code helpful but I'm not a fan of dynamic menus, I'll integrate the option as a startup flag
While testing, the new code will be available in experimental branch
