### ISSUE TITLE
[REQUEST] Port?

### ISSUE THREAD

**Issue by nynhex** [realtho/PartyLoud#6]
do you mind if i port this to golang or ruby and give attribution?

**Comment by realtho** [comment]
I'm absolutely okay with this
I'll add link to your port in readme file

**Comment by nynhex** [comment]
@realtho sounds good, and thanks for spurring the idea.  i kind went down the rabbit hole and thought of traffic obfuscation with an isolate vpn tunnel in the center.  but maybe that's a fork of the project

**Comment by realtho** [comment]
I've never thought about his feature. Currently I'm working on DNS requests randomization but, If you're familiar with VPNs and you want to write some code to enable this functionality, feel free to make a pull request in the experimental branch, even just to show me the road.
Also, I'm changing the code structure so, please if you're thinking about writing some VPN-related code place it under a file src/vpn.sh
