### ISSUE TITLE
[BUG] Code fixes

### ISSUE THREAD

**Issue by ghost** [realtho/PartyLoud#8]
**Describe the bug** <-- it's not a bug.
Code fixes

1. I saw you use a lot of `tput`s. As far as I know, `tput` behaves differently between different terminals and operating systems. There is a more universal and faster way which is using escape sequences. You can find those [here](https://github.com/dylanaraps/pure-bash-bible).
2. As for flag concatenation, I think it's better to use:
`while test "${#}" -gt 0; do`
3. As for the **clearLines** function, I think it does many useless operations. I was using your one for a script I'm creating, but then I've rewritten it and I came up with:
```
function clearLines() {
  local i
  for ((i=0; i<"${1}"; i++)); do
    printf "\e[2K"  # Clear entire line
    printf "\e[1A"  # Up one line
  done
}
```
(You may need to change the order of the two printfs or do <= in the for loop to adapt it to your code)
4. Line 126, use this condition instead:
`if [[ -n "${ProxyOpt}" ]]; then`
5. Speaking about the DNS file, in the checkDNS function use `return` instead of `echo`. So that the condition at line 17 will spawn one less subshell:
`while checkDNS "$Dns && [[ Retry < 5 ]]; do`
Also, at line 53, use this condition instead
`if [[ -n "${Ip}" ]] && [[ -n "${Port}" ]]; then`
6. Speaking about the tools.sh file, I suggest to change the condition at line 30. As for now it spawns a new subshell in each loop and it is a slowdown:
`if command -v "$COMMAND"; then`

I haven't tested the code I wrote, but I'm pretty sure it works.
Also, I suggest you to debug your code using [shellcheck](https://github.com/koalaman/shellcheck).
Sorry for any English mistake (I am Italian).

**Comment by realtho** [comment]
Ciao sono italiano anche io ahaha
Purtroppo non posso lavorare allo script perché sono sommerso di lavoro per gli esami dell'Università (mi sto per laureare)
Comunque alcune cose che mi hai indicato le sto già correggendo nel branch experimental
Le versioni alpha dello script usavano solo sequenze escape ascii, le ho rimosse proprio perché tra Mac e Debian c'erano conflitti
Per quanto riguarda return non è così semplice, return è valido solo per i tipi interi, non funziona (o comunque non funziona bene) con le stringhe
Con tutta probabilità non ci lavorerò almeno fino alla metà di luglio, comunque grazie mille per i consigli

**Comment by railand** [comment]
> Le versioni alpha dello script usavano solo sequenze escape ascii, le ho rimosse proprio perché tra Mac e Debian c'erano conflitti

Ah. Secondo la mia esperienza non ci sono state incompatibiità fra il terminale di macOS (High Sierra) e quello di debian (uso gnome-terminal)... ma non ne avevo provate molte, sicuramente ne sai più di me :D

> Per quanto riguarda return non è così semplice, return è valido solo per i tipi interi, non funziona (o comunque non funziona bene) con le stringhe

Ma in quel caso non stai usando stringhe. Semplicemente se la condizione è vera stampi 1 e 0 altrimenti, perciò oltre al tempo necessario per invocare `echo`, devi aggiungere quello necessario per eseguire il comando in una subshell... Se provassi a cambiare con `return` e come condizione mettere 
`while checkDNS "$Dns" && [[ Retry < 5 ]]; do` dovrebbe funzionare, al limite mi sto sbagliando =)

> Purtroppo non posso lavorare allo script perché sono sommerso di lavoro per gli esami dell'Università (mi sto per laureare)

Buona fortuna!
